'use strict';
const D=window.WIKI_DATA,$=s=>document.querySelector(s),E={Fire:'火',Water:'水',Wind:'風',Light:'光',Dark:'闇'},roles={Tank:'タンク',Attacker:'アタッカー',Sorcerer:'魔法',Healer:'ヒーラー',Buffer:'支援',Debuffer:'弱体'},beats={Fire:'Wind',Wind:'Water',Water:'Fire',Light:'Dark',Dark:'Light'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),link=(type,id,label)=>`<a href="#${type}/${encodeURIComponent(id)}">${esc(label)}</a>`,tag=t=>`<span class="badge">${esc(t)}</span>`,el=e=>`<span class="element-${esc(e)}">● ${E[e]||'—'}</span>`,portrait=c=>`<span class="portrait" role="img" aria-label="${esc(c.name)}" style="background-position:-${c.portrait%12*192}px -${Math.floor(c.portrait/12)*192}px"></span>`,character=id=>D.characters.find(c=>c.id===id),charLink=id=>link('character',id,character(id)?.name||id);
const table=(heads,rows)=>`<div class="table-wrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v??'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`,section=(title,more='',url='')=>`<div class="section-title"><h2>${title}</h2>${url?`<a href="#${url}">${more} →</a>`:''}</div>`,panel=(title,body)=>`<section class="panel"><h2>${title}</h2>${body}</section>`,date=t=>new Date(t).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}),nowJST=()=>new Date(Date.now()+9*3600000),currentEvent=()=>{const n=nowJST();return D.events.find(e=>e.month===n.getUTCMonth()+1&&e.half===(n.getUTCDate()<16?1:2));},period=e=>{const y=nowJST().getUTCFullYear();return {start:Date.UTC(y,e.month-1,e.half===1?1:16)-9*3600000,end:Date.UTC(y,e.month-1+(e.half===2?1:0),e.half===1?16:1)-9*3600000};},weak=e=>Object.keys(beats).find(k=>beats[k]===e),item=id=>[...D.equipment,...D.decorations].find(e=>e.id===id),itemLink=id=>link('equipment',id,item(id)?.name||id);
const navigation=[['home','⌂','トップ'],['guide','◇','初心者ガイド'],['characters','♧','キャラクター'],['rankings','♕','キャラランキング'],['events','✦','イベント・ボス攻略'],['gacha','✧','召喚・スケジュール'],['dungeons','♜','ダンジョン'],['contracts','▤','酒場・依頼'],['ranks','△','パーティランク'],['growth','+','パーティ育成'],['formation','♟','パーティ編成'],['equipment','⚒','装備・アイテム'],['coop','⚑','共闘・フレンド'],['npcs','♙','NPC冒険者'],['camp','♨','キャンプ'],['story','▱','ストーリー'],['systems','◎','戦闘・データ'],['faq','?','よくある質問']];
$('#edition').textContent=D.updated;
function charCard(c){return `<a class="card character-card" href="#character/${c.id}"><div class="portrait-wrap">${portrait(c)}</div><div class="card-body"><span class="stars">${'★'.repeat(c.rarity)}</span><h3>${esc(c.name)}</h3><p>${el(c.el)} · ${roles[c.role]||esc(c.role)}</p>${c.eventOnly?tag('限定'):tag('常設')}<p>${esc(c.skill)}</p></div></a>`;}
function eventCard(e){return `<a class="card" href="#event/${e.id}"><img class="card-image" src="${e.id}.webp" alt="${esc(e.boss)}" loading="lazy" width="1000" height="563"><div class="card-body"><span class="month">${e.month}月${e.half===1?'前半':'後半'}</span><h3>${esc(e.boss)}</h3><p>${esc(e.theme)} · ${el(e.element)}</p>${tag('F〜S / 最大18人')}</div></a>`;}
function pickup(){const s=D.gacha.pickupSchedule,w=7*86400000,i=Math.floor((Date.now()-Date.parse(s.anchor))/w),slot=((i%s.weeks.length)+s.weeks.length)%s.weeks.length;return {...s.weeks[slot],slot,start:Date.parse(s.anchor)+i*w,end:Date.parse(s.anchor)+(i+1)*w};}
function home(){const e=currentEvent(),p=period(e),g=pickup(),c=character(e.featured),pc=character(g.featured),weekdays=D.gacha.weekdayPools.filter(p=>p.day===nowJST().getUTCDay());return `<div class="crumb">冒険者のための攻略・データベース</div><section class="hero"><img src="${e.id}.webp" alt="${esc(e.boss)}のイベントイラスト" width="1000" height="563"><div class="hero-copy"><span class="eyebrow">SEASONAL EXPEDITION · 開催中</span><h1>${esc(e.boss)}<br>季節の討伐祭へ。</h1><p>${esc(e.theme)}。仲間と力を合わせて限定戦利品を集めよう。<br>F〜Dは5階層、C以上は10階層へ挑戦できます。</p><a class="button" href="#event/${e.id}">ボスと戦利品を調べる →</a></div></section><section class="today"><div><small>開催期間 / 日本時間</small><b>${date(p.start)} — ${date(p.end)}</b><small data-countdown="${p.end}"></small></div><div><small>本日の曜日限定召喚</small><b>${weekdays.length?weekdays.map(p=>charLink(p.featured)).join(' / '):'本日の曜日限定召喚はありません'}</b><small>曜日限定ダンジョンの設定はありません</small></div><div><small>今週のピックアップ</small><b>${charLink(pc.id)} · ★5</b><small>木曜0:00更新 / ${date(g.end)}まで</small></div></section>${section('灯がつなぐ、新しい仲間。','召喚と排出率','gacha')}<div class="split"><a class="card" href="#character/${c.id}"><div style="display:flex;align-items:center"><div class="portrait-wrap">${portrait(c)}</div><div class="card-body"><span class="badge live">期間限定</span><h3>${esc(c.name)}</h3><p>${esc(c.skill)}</p><span class="stars">★★★★★</span></div></div></a><a class="card" href="#character/${pc.id}"><div style="display:flex;align-items:center"><div class="portrait-wrap">${portrait(pc)}</div><div class="card-body">${tag('今週のピックアップ')}<h3>${esc(pc.name)}</h3><p>${esc(pc.skill)}</p><span class="stars">★★★★★</span></div></div></a></div><section class="panel"><span class="eyebrow">このゲームが目指すこと</span><h2>ソシャゲの楽しさを、暮らしに無理のないペースで。</h2><p>『ダンジョンの入口でキャンプでもしようよ。』は、「ソシャゲ中毒から離れるきっかけをつくりたい」という思いを、開発コンセプトのひとつにしています。</p><p>追加課金なし。召喚に使う星の石は、アプリを閉じている間も30分に1個チャージされます。やりすぎを防ぐためのスタミナも、基本10分に1回復。足りなくなったら、キャンプでひと休み。遊んでいない時間も、次の冒険の準備になります。</p><p>それでも、季節を追う楽しさはたっぷり。年間24のイベントをめぐり、フレンドの冒険者カードやNPCパーティと擬似的なアライアンスを組んで、最大18人で巨大ボスに挑めます。</p><p class="note">共闘はNPCが操作する擬似マルチプレイです。フレンド本人とリアルタイムで接続する仕組みではありません。</p></section>${section('はじめての冒険','初心者ガイド','guide')}<div class="grid wide">${[['guide','01','まずは、キャンプから','チュートリアル10連召喚から編成、最初の物語まで。'],['systems','02','属性と役割を知る','火・水・風の相性と、前衛を守る考え方。'],['contracts','03','次の依頼を選ぶ','ランク・階層・報酬から行き先を探そう。']].map(([id,n,t,s])=>`<a class="card card-body" href="#${id}"><span class="eyebrow">FIELD GUIDE ${n}</span><h3>${t}</h3><p>${s}</p></a>`).join('')}</div>${section('仲間を知る','134人の図鑑','characters')}<div class="grid">${['aster','kuro','miel','una'].map(id=>charCard(character(id))).join('')}</div>${section('季節をめぐる冒険','年間24イベント','events')}<div class="grid wide">${[e,...D.events.filter(x=>x.id!==e.id).sort((a,b)=>((a.month-e.month+12)%12)-((b.month-e.month+12)%12))].slice(0,3).map(eventCard).join('')}</div>${section('冒険の準備')}<div class="linklist">${['equipment','camp','npcs','coop'].map(id=>`<a href="#${id}">${navigation.find(n=>n[0]===id)[2]}</a>`).join('')}</div>`;}
function characters(){return `<span class="eyebrow">COMPANIONS</span><h1>キャラクター図鑑</h1><p class="muted">134人の仲間を、属性・役割・レア度から探す。数値は初期基礎値です。</p><div class="filterbar"><input id="char-query" type="search" aria-label="キャラ名・スキル検索" placeholder="名前・スキルで検索"><select id="rarity" aria-label="レア度"><option value="">全レア度</option><option>5</option><option>4</option><option>3</option></select><select id="element" aria-label="属性"><option value="">全属性</option>${Object.entries(E).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><select id="role" aria-label="役割"><option value="">全ロール</option>${Object.entries(roles).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><select id="limited" aria-label="入手区分"><option value="">常設・限定</option><option value="yes">限定</option><option value="no">常設</option></select></div><p id="result-count" class="count" aria-live="polite"></p><div id="char-results" class="grid"></div>`;}
function filterCharacters(){const q=$('#char-query').value.trim().toLowerCase(),list=D.characters.filter(c=>(c.name+c.skill+c.skillDescription).toLowerCase().includes(q)&&(!$('#rarity').value||c.rarity==$('#rarity').value)&&(!$('#element').value||c.el==$('#element').value)&&(!$('#role').value||c.role==$('#role').value)&&(!$('#limited').value||(c.eventOnly?'yes':'no')==$('#limited').value));$('#result-count').textContent=`${list.length}人 / 全134人`;$('#char-results').innerHTML=list.map(charCard).join('')||'<p class="empty">条件に一致する仲間はいません。</p>';}
function skillPower(c,a,seasonal=false){
 const n=x=>Number(Number(x).toFixed(3)),pct=x=>`${n(x*100)}%`;
 if(a.effect==='barrier')return `被ダメージ ${pct(a.reduction)}軽減`;
 if(a.effect==='meadow')return `最大HPの${pct(a.healPercent)}を${a.interval}秒ごとに回復`;
 if(a.effect==='starlight')return `${a.interval}秒ごとにSP +${a.spAmount}`;
 if(a.effect==='tailwind')return `攻撃間隔 ×${a.intervalMultiplier}`;
 if(['rally','fracture'].includes(a.effect))return `${a.effect==='rally'?'与ダメージ':'敵の被ダメージ'} ×${a.multiplier}`;
 if(a.effect==='inferno')return `攻撃力 ×${a.power} / ${a.interval}秒ごと`;
 if(!seasonal&&c.role==='Buffer')return `攻撃力 ×${a.power}`;
 if(!seasonal&&c.role==='Healer')return `回復量：攻撃力 ×${a.power}`;
 const parts=[];
 if(a.power)parts.push(`攻撃力 ×${a.power}${a.hits?` ×${a.hits}回（合計${n(a.power*a.hits)}倍）`:''}`);
 if(a.healRange)parts.push(`回復量：攻撃力 ×${a.healRange[0]}〜${a.healRange[1]}（発動ごとにランダム）`);else if(a.heal)parts.push(`回復量：攻撃力 ×${a.heal}`);
 if(a.bossBonus)parts.push(`ボスへのダメージ +${pct(a.bossBonus)}`);
 if(a.shield)parts.push(`シールド：最大HPの${pct(a.shield)}`);
 if(a.regen)parts.push(`継続回復：最大HPの${pct(a.regen)} / 2秒`);
 if(a.revive)parts.push(`最大HPの${pct(a.revive)}で復活`);
 return parts.join(' / ')||'直接ダメージ倍率なし（効果量は説明参照）';
}
function characterSkills(c){const entries=c.seasonalUltimate?[['通常スキル',c.normalSkill],['必殺技',c.seasonalUltimate]]:[['必殺技',{...c.ability,name:c.skill,description:c.skillDescription}]];return entries.map(([label,a])=>panel(`${label}：${esc(a.name)}`,`<p>${esc(a.description||'')}</p><p class="skill-power"><strong>基礎倍率・効果量：</strong>${esc(skillPower(c,a,!!c.seasonalUltimate))}</p>${table(['CT','消費SP','対象'],[[`${a.cooldown??'—'}秒`,label==='通常スキル'?0:c.ability?.cost??'—',esc(a.scope||({enemy:'敵単体',enemies:'敵全体',self:'自分',allies:'味方全体',ally:'味方単体',random:'敵ランダム',fallen:'戦闘不能の味方'}[a.target])||'説明参照')]])}${a.duration?`<p>効果時間：${a.duration}秒</p>`:''}<p class="note">基礎設定値です。実際のダメージ・回復量は防御力、属性相性、装備や強化・弱体効果などで変わります。</p>`)).join('');}
function characterPage(id){const c=character(id);if(!c)return missing();const a=c.ability||{},event=D.events.find(e=>e.featured===id),same=D.characters.filter(x=>x.role!==c.role&&x.el===c.el).slice(0,4);return `<div class="crumb"><a href="#characters">キャラクター</a> / ${esc(c.name)}</div><article class="detail-hero"><div class="portrait-wrap">${portrait(c)}</div><div class="body"><span class="stars">${'★'.repeat(c.rarity)}</span><h1>${esc(c.name)}</h1><p>${el(c.el)} · ${roles[c.role]} · ${esc(c.race)}</p>${tag(c.eventOnly?'限定キャラ':'常設キャラ')}${tag(c.personality)}<div class="stat-grid">${[['HP',c.hp],['攻撃力',c.atk],['防御力',c.def]].map(([n,v])=>`<div class="stat"><small>初期${n}</small><b>${v??'—'}</b></div>`).join('')}</div></div></article>${characterSkills(c)}${panel('入手と育成',`<p>${event?`イベント ${link('event',event.id,event.boss)} の限定召喚で登場。`:c.eventOnly?'対象の限定召喚で登場します。':'常設召喚の対象です。'} ${link('gacha','', '召喚の仕組みを確認')}</p><p>EXPでレベルアップ。重複加入はレベル上限の解放につながります。仲間詳細の訓練では現在レベル×100 Gで1レベル上げられます。上限は主人公レベル×0.75（切り捨て）と仲間自身の上限の低い方です。主人公は訓練できず、冒険で育てます。</p>`)}${panel('編成の考え方（攻略の提案）',`<p>${{Tank:'前衛で敵の攻撃を引き受け、回復役と組ませます。',Healer:'前衛を支えます。複数対象の回復か単体回復かをスキル説明で確認しましょう。',Attacker:'有利属性のボスに火力を集中させる役です。',Sorcerer:'範囲と消費SPを確認し、複数の敵を処理する役として組み込みます。',Buffer:'火力役と回復役を用意してから支援枠として加えます。',Debuffer:'敵の弱体効果と持続時間を確認し、火力役が攻撃する時間を作ります。'}[c.role]}</p><p>同属性でも役割が異なる仲間を組み合わせると、編成を補いやすくなります。順位付けは行っていません。</p><div class="grid">${same.map(charCard).join('')}</div>`)}${panel('キャンプでの一面',`<p>${esc(c.personality)}な${esc(c.race)}。行動：${(c.actions||[]).map(esc).join(' / ')||'ゲーム内のキャンプで確認できます。'}</p>`)}`;}
function events(){return `<span class="eyebrow">SEASONS OF ADVENTURE</span><h1>イベント・ボス攻略</h1><p>月の前半は1日〜16日0:00、後半は16日〜翌月1日0:00（JST）。全ランクから参加でき、C以上で10階層が解放されます。</p><div class="grid wide">${[...D.events].sort((a,b)=>a.month-b.month||a.half-b.half).map(eventCard).join('')}</div>`;}
function eventPage(id){const e=D.events.find(e=>e.id===id);if(!e)return missing();const p=period(e),w=weak(e.element);return `<div class="crumb"><a href="#events">イベント</a> / ${esc(e.boss)}</div><img class="art-full" src="${id}.webp" alt="${esc(e.boss)}" width="1000" height="563"><div class="panel"><span class="eyebrow">${e.month}月${e.half===1?'前半':'後半'} · ${esc(e.theme)}</span><h1>${esc(e.boss)}</h1><p>${date(p.start)} 〜 ${date(p.end)} JST</p><p>ボス属性 ${el(e.element)} / 攻略に有利 ${el(w)}</p><p>F〜D：5階層の控えめな戦利品。C〜S：10階層の限定装備・装飾品。</p>${table(['ランク','階層','ボスHP','攻撃力','目安戦力','報酬'],e.difficulties.map(q=>{const b=q.waves.at(-1).enemies[0];return [q.rank,q.waves.length,b.hp.toLocaleString(),b.atk,q.recommendedPower.toLocaleString(),`${q.rewards.xp} EXP / ${q.rewards.gold} G`]}))}</div>${panel('ボスの行動と準備',`<h3>18人で攻略しよう</h3><img class="art-full" src="alliance-battle.webp" alt="3パーティ・18人の冒険者が巨大な竜と戦う共闘イラスト" width="1672" height="941" loading="lazy"><p class="note">アライアンス共闘のイメージイラストです。</p><p>NPCパーティを募集したり、SNSで冒険者カードを共有してフレンドを増やしたりして、最大18人のアライアンスで巨大ボスに挑みましょう。強いフレンドのパーティが擬似マルチに参加すれば、格上のボスも攻略しやすくなります。</p><p class="highlight">参加するパーティはランダムです。特定のNPCやフレンドを指名することはできず、強いフレンドが必ず参加するとは限りません。フレンド本人とのリアルタイム通信ではなく、登録した冒険者カードをもとにNPCが操作する擬似共闘です。</p><p>ボスのCTは挑戦ランクごとの範囲から、初回とスキル使用ごとにランダムで決まります。ゲームの戦闘画面ではボスCTを表示しません。</p>${table(['挑戦ランク','ボスのCT'],[...'FEDCBAS'].map((r,i)=>[r,`${16-i}〜${17.5-i}秒`]))}<p>前方範囲1.4倍と全体1.2倍を共有CTで交互に使います。前方範囲の対象は各パーティの生存する最前列です。</p><p>攻略の提案：前衛の耐久と全体攻撃後の立て直しを優先し、${E[w]}属性の攻撃役を添えましょう。単独は高難度のため、育成が足りない場合は${link('coop','','アライアンス')}を活用します。</p><div class="grid">${D.characters.filter(c=>c.el===w&&['Tank','Healer','Attacker','Sorcerer'].includes(c.role)&&!c.eventOnly).slice(0,4).map(charCard).join('')}</div>`)}${panel('限定戦利品',`<p>ボス撃破時65%で、その挑戦ランクの3種から等確率で1つ。単独は獲得確定、共闘は参加パーティ間のダイスで獲得者を決めます。</p>${table(['挑戦ランク','戦利品3種'],e.difficulties.map(q=>[q.rank,q.dropItems.map(itemLink).join(' / ')]))}<p class="note">同じキャンプ装飾品の重複獲得は500 Gに変換。交換所・交換優先度の設定はありません。</p>`)}${panel('同時期の限定キャラクター',`<div class="grid">${charCard(character(e.featured))}</div>`)}`;}
function dungeons(){return `<h1>ダンジョン一覧</h1><p>階層数・敵・報酬は選んだ依頼によって変わります。個別ページから目的の依頼へ進めます。</p><div class="grid wide">${D.dungeons.map(d=>`<a class="card" href="#dungeon/${d.id}"><img class="card-image" src="${d.background.split('/').pop().replace('.png','.webp')}" alt="${esc(d.name)}" loading="lazy"><div class="card-body"><h3>${esc(d.name)}</h3><p>${esc(d.subtitle)}</p><p>基準戦力 ${d.recommendedPower.toLocaleString()}</p></div></a>`).join('')}</div>${section('季節限定のダンジョン','イベント攻略','events')}<p>季節イベントは通常の依頼とは異なる敵とドロップを持ちます。</p>`;}
function jobsTable(jobs){return table(['依頼','ランク','種類','階層','報酬'],jobs.map(c=>[link('contract',c.id,c.name),c.requiredRank,esc(c.type),c.targetFloor,`${c.rewards.gold} G / ${c.rp} RP`]));}
function dungeonPage(id){const d=D.dungeons.find(d=>String(d.id)===id);if(!d)return missing();return `<div class="crumb"><a href="#dungeons">ダンジョン</a> / ${esc(d.name)}</div><img class="art-full" src="${d.background.split('/').pop().replace('.png','.webp')}" alt="${esc(d.name)}"><h1>${esc(d.name)}</h1><p>${esc(d.miniStory)}</p>${panel('入手できる装備',`<p>${esc(d.dropStory)}</p>${table(['レア度','抽選率'],d.dropTable.map(r=>['★'.repeat(r.rarity),`${r.rate*100}%`]))}<p>${D.equipment.filter(i=>i.set==='normal'&&d.dropTable.some(r=>r.rarity===i.rarity)).map(i=>itemLink(i.id)).join(' / ')}</p>`)}${section('この迷宮へ向かう依頼')}${jobsTable(D.contracts.filter(c=>c.dungeonId===d.id))}`;}
function contractsPage(){return `<h1>酒場・依頼一覧</h1><p>帰還ごとに依頼が更新され、各ランクの候補から2〜4件が掲示されます。この一覧は全候補です。</p><div class="filterbar"><input id="job-query" type="search" placeholder="依頼名・目的地を検索" aria-label="依頼検索"><select id="job-rank" aria-label="依頼ランク"><option value="">全ランク</option>${D.ranks.map(r=>`<option>${r.name}</option>`).join('')}</select></div><div id="job-results"></div>`;}
function filterJobs(){const q=$('#job-query').value;$('#job-results').innerHTML=jobsTable(D.contracts.filter(c=>(c.name+c.quest.name).includes(q)&&(!$('#job-rank').value||c.requiredRank==$('#job-rank').value)));}
function contractPage(id){const c=D.contracts.find(c=>c.id===id);if(!c)return missing();const q=c.quest;return `<div class="crumb"><a href="#contracts">依頼</a> / ${esc(c.name)}</div><h1>${esc(c.name)}</h1>${tag(c.requiredRank+'ランク')}${tag(c.type)}<p>${esc(c.description)}</p><p>行き先：${link('dungeon',c.dungeonId,q.name)} / スタミナ ${c.stamina??1}</p>${table(['報酬G','RP','EXP','育成SP','素材'],[[c.rewards.gold,c.rp,q.rewards.xp,q.rewards.sp,q.rewards.materials]])}${panel('階層ごとの敵',table(['階層','敵','属性','HP','攻撃力'],q.waves.flatMap((w,i)=>w.enemies.map(e=>[i+1,esc(e.name)+(e.boss?'【ボス】':''),el(e.el),e.hp,e.atk]))))}<p class="highlight">目安戦力 ${q.recommendedPower.toLocaleString()}。5階層以降は敵スキルが追加されます。ボス属性と前衛の耐久を確認しましょう。</p><p>${esc(q.dropStory)}</p>`;}
function equipmentPage(id){if(id){const i=item(id);if(!i)return missing();const es=D.events.filter(e=>e.difficulties.some(q=>q.dropItems.includes(id)));return `<div class="crumb"><a href="#equipment">装備・アイテム</a> / ${esc(i.name)}</div><h1>${esc(i.name)}</h1>${tag(i.slot==='decoration'?'キャンプ装飾':({weapon:'武器',armor:'防具',accessory:'アクセサリー'}[i.slot]||i.slot))}<p class="stars">${'★'.repeat(i.rarity||0)}</p><p>${esc(i.description||'追加効果なし')}</p>${table(['能力','補正'],Object.entries(i.stats||{}).map(([k,v])=>[({atk:'攻撃力',def:'防御力',hp:'HP'}[k]||k),`+${v}`]))}${panel('入手先',es.length?es.map(e=>eventCard(e)).join(''):`<p>${i.set==='normal'?'通常ダンジョンの該当レア度抽選で獲得。':'マスターデータで個別の入手先が指定されていません。'}</p><p><a href="#dungeons">ダンジョンとドロップ率を調べる →</a></p>`)}${i.slot==='decoration'?'<p>同時に有効化できる装飾品は2個です。</p>':''}`;}return `<h1>装備・キャンプ装飾品</h1><p>入手先からイベント・ダンジョンへたどれます。交換所やクラフトの未実装レシピは掲載していません。</p><div class="filterbar"><input id="item-query" type="search" aria-label="アイテム検索" placeholder="名前・効果で検索"><select id="item-slot" aria-label="装備部位"><option value="">全部位</option><option value="weapon">武器</option><option value="armor">防具</option><option value="accessory">アクセ</option><option value="decoration">キャンプ装飾</option></select></div><div id="item-results"></div>${panel('素材について','<p>依頼で手に入る「素材」は共通の資源です。架空の収穫物名や未設定の採集階層は掲載していません。獲得量は各依頼ページで確認できます。</p>')}`;}
function filterItems(){const q=$('#item-query').value,s=$('#item-slot').value;$('#item-results').innerHTML=table(['名称','種別','レア度','能力・効果'],[...D.equipment,...D.decorations].filter(i=>(i.name+(i.description||'')).includes(q)&&(!s||i.slot===s)).map(i=>[itemLink(i.id),({weapon:'武器',armor:'防具',accessory:'アクセ',decoration:'装飾'}[i.slot]||i.slot),'★'.repeat(i.rarity||0),esc(i.description||Object.entries(i.stats||{}).map(([k,v])=>`${k} +${v}`).join(' / '))]));}
function gachaPage(){const p=pickup(),e=currentEvent(),rates=D.gacha.rates;return `<span class="eyebrow">NEW ENCOUNTERS</span><h1>召喚・年間スケジュール</h1><p>1回につき星の石${D.config.summonCost}個。石は30分で1個チャージ、所持上限なし。最初のチュートリアル10連召喚はチュートリアルで受け取れます。</p><section class="panel"><h2>連続ログインボーナス</h2><p>1日目は星の石20個、2日連続25個、3日連続30個、4日連続35個、5日連続40個。5日間で合計150個を受け取れます。</p><p>5日連続ボーナスを受け取ると、次は1日目にリセット。受け取らない日がある場合も1日目に戻ります。毎日0:00（日本時間）更新。最初の受け取りはチュートリアル完了後です。</p></section><div class="split">${panel('今週のピックアップ',`${charCard(character(p.featured))}<p>${date(p.start)} 〜 ${date(p.end)} JST</p>`)}${panel('今期の限定召喚',`${charCard(character(e.featured))}<p>${link('event',e.id,e.theme)}と同じ期間に開催。</p>`)}</div>${panel('排出率',`${table(['レア度','合計排出率'],rates.map((r,i)=>['★'.repeat(i+3),`${(r*100).toFixed(1)}%`]))}<p>ピックアップ対象は★5枠の${D.gacha.pickupShare*100}%を占めます。対象キャラの1回あたり排出率は${(rates[2]*D.gacha.pickupShare*100).toFixed(2)}%（★5対象が複数いる場合）。残りは同レア度の対象キャラへ均等に配分されます。</p><p>限定キャラは該当する召喚のみで排出。通常召喚では常設キャラが対象です。</p>`)}${section('曜日限定召喚')}${table(['曜日','対象キャラ'],D.gacha.weekdayPools.map(p=>[p.label+'曜日',charLink(p.featured)]))}${section('これから52週間のピックアップ')}${table(['期間（JST）','ピックアップ'],Array.from({length:52},(_,i)=>{const entry=D.gacha.pickupSchedule.weeks[(p.slot+i)%D.gacha.pickupSchedule.weeks.length];return [`${date(p.start+i*604800000)} 〜 ${date(p.start+(i+1)*604800000)}`,charLink(entry.featured)]}))}${section('限定召喚の年間カレンダー')}${table(['時期','限定キャラ','イベント'],[...D.events].sort((a,b)=>a.month-b.month||a.half-b.half).map(e=>[`${e.month}月${e.half===1?'前半':'後半'}`,charLink(e.featured),link('event',e.id,e.boss)]))}`;}
function npcPage(id){if(id){const n=D.npcs.find(n=>n.id===id);if(!n)return missing();return `<h1>${esc(n.name)}</h1>${tag(n.personality)}${tag(n.frequency)}<p>登録戦力 ${n.power.toLocaleString()} / 編成レベル ${n.level}</p><p>活動時間（JST）：${[...n.hours].sort((a,b)=>a-b).map(h=>h+'時').join(' / ')}</p><p class="note">活動時間は出現候補の判定です。必ず酒場に出現・参戦するという意味ではありません。表示戦力はプロフィールの基準値です。</p><div class="grid">${n.party.map(id=>charCard(character(id))).join('')}</div>${panel('共闘での使い方（攻略の提案）','<p>前衛・回復役の人数を確認して、自分のパーティだけに回復を任せすぎないようにしましょう。実際の参加はゲーム内の抽選で決まります。</p>')}`;}return `<h1>NPC冒険者図鑑</h1><p>酒場ですれ違う10人の冒険者。活動時間と実際の使用キャラを確認できます。</p><div class="grid wide">${D.npcs.map(n=>`<a class="card card-body" href="#npc/${n.id}">${portrait(character(n.favorite||n.party[0]))}<h3>${esc(n.name)}</h3>${tag(n.personality)}<p>登録戦力 ${n.power.toLocaleString()} · ${esc(n.frequency)}</p><p>${n.party.map(id=>esc(character(id)?.name)).join(' / ')}</p></a>`).join('')}</div>`;}
function guides(page){const content={
 guide:['初心者ガイド',`<p>このゲームは買い切り・オフラインを中心とした冒険RPG。まずはチュートリアル10連召喚で仲間を迎え、役割を分けた6人パーティを作りましょう。</p><h2>最初に進めること</h2><ol><li>キャンプから酒場を開き、体験依頼を受ける。</li><li>ダンジョンを攻略してキャンプへ戻る。</li><li>召喚から最初のチュートリアル10連召喚を受け取り、キャンプへ戻る。</li><li>仲間からパーティを編成する。</li><li>ストーリーを読み、そのまま物語のダンジョンへ進む。</li><li>キャンプへ戻り、酒場で次の依頼を受ける。</li><li>依頼を達成し、キャンプで最初のログインボーナスを受け取る。</li></ol><h2>チュートリアル10連召喚のあとに育てたい役割</h2><p>回復役を1人、前衛を支えるタンクを1人確保し、残りを火力・支援に振り分けるのが出発点です。これは攻略上の提案で、固定の最強編成ではありません。</p><div class="grid">${D.gacha.guaranteed.map(id=>charCard(character(id))).join('')}</div><h2>毎日の旅支度</h2><ul><li>ログインスタンプを受け取る。</li><li>キャンプバフとスタミナを確認する。</li><li>開催中イベントの終了日時を確認する。</li><li>欲しい装備が出る依頼を選ぶ。</li><li>出発前に装備・前衛・回復役を確認する。</li></ul><p>石を使う前に${link('gacha','','召喚カレンダー')}で対象キャラを確認しましょう。リセマラを前提とする必要はありません。</p>`],
 ranks:['パーティランク',`<p>ランクは依頼で獲得する累計RPで上がります。キャラクターのレベルとは別の指標です。</p>${table(['ランク','必要累計RP','次のランクまで'],D.ranks.map((r,i)=>[r.name,r.rp.toLocaleString(),D.ranks[i+1]?D.ranks[i+1].rp-r.rp:'最高ランク']))}<p>ストーリーは各ランク10章。イベントはF〜Dで5階層、C〜Sで10階層へ挑戦できます。</p><p><a href="#contracts">現在のランクで受けられる依頼を探す →</a></p>`],
 coop:['共闘・フレンド',`<h2>最大18人のアライアンス</h2><p>自分の6人パーティ＋最大2組のNPCパーティで挑みます。募集は30秒。2パーティが揃うか時間切れで出発します。</p>${table(['攻略方法','イベント消費スタミナ','ドロップ時'],[['単独','1','自分が獲得'],['アライアンス','2','参加パーティのダイスで最高値の組が獲得']])}<h2>大型ボスの戦利品</h2><p>ドロップ率は65%。対象3種から1種を抽選します。アライアンスは全員への配布ではありません。同値時は再抽選されます。</p><h2>フレンドの参戦</h2><p>冒険者カードのQRからフレンドを登録すると、募集時に確率で参加します。共有時点のパーティ情報を使う擬似マルチです。相手とリアルタイムに通信するオンライン協力プレイではありません。</p><h2>緊急共闘</h2><p>酒場で発生する緊急共闘は、定期開催の季節イベントとは別です。遭遇はゲーム内で抽選されるため、Wikiに「今週必ず出るボス」として表示しません。</p><p><a href="#npcs">参加するNPCを調べる →</a></p>`],
 growth:['パーティ育成',`<p>主人公と一緒に無理のない依頼をこなし、レベル・訓練・装備でパーティを育てましょう。</p>
<h2>経験値を集める3つの方法</h2>
<ul><li><b>ダンジョン攻略：</b>酒場の依頼を攻略します。深い階層ほど報酬EXPは多くなりますが、クリアできる難易度を選びましょう。</li><li><b>放置：</b>チュートリアル完了後、アプリを閉じている間は編成中の仲間に10分で1 EXP。再開時に精算され、装飾品で増加できます。</li><li><b>ストーリー：</b>スタミナ消費0で少量のEXP・G。物語を進めながら育成できます。</li></ul>
<h2>5階層以上は準備してから</h2><p>5階層から雑魚敵も範囲スキルを使い、被害が増えます。無理をして敗れるより、低ランク・浅い階層で装備とレベルを整えるのがおすすめです。ボスの属性とおすすめ属性も確認しましょう。</p>
<h2>主人公を必ず編成しよう</h2><div class="portrait-wrap">${portrait(character('aster'))}</div><p>ゴールド訓練の上限は主人公レベルの<strong>4分の3（端数切り捨て）</strong>です。主人公Lv.20なら仲間をLv.15まで訓練できます。主人公自身はゴールド訓練ができないため、一緒に冒険して育てましょう。自動編成では主人公が前衛に入ります。</p>
<h2>ゴールドで仲間を訓練する</h2><ol><li>下部メニューの「仲間」を開きます。</li><li>育てたいキャラをタップし、詳細画面を下へスクロールします。</li><li>「訓練（ゴールドでレベルアップ）」を押します。スキル説明の下・装備欄の上にあります。</li><li>上限・費用を確認し、「Gを使って1レベル上げる」を押します。</li></ol>
<figure><img src="training-screen.png" alt="ミエルの訓練画面。主人公Lv20、訓練上限Lv15、現在Lv5からLv6へ500Gで訓練する例" style="width:100%;max-width:520px;height:auto"><figcaption>実装済みの訓練画面を説明用データで撮影。数値は一例です。</figcaption></figure>
<p>費用は<strong>現在レベル×100 G</strong>。1回で1レベル上がり、現在のEXPは引き継ぎます。キャラ自身のレベル上限も超えられません。ボタンが押せないときは、ゴールド不足・主人公とのレベル差・キャラの上限を確認してください。</p>
<h2>装備を揃えよう</h2><p>武器・防具・アクセサリーで能力値を上げられます。仲間の詳細の「装備を変更」から手動で選ぶか、「自動装備」でおすすめに入れ替えられます。</p><p>編成画面の「自動装備」→「自動で装備する」なら、編成中の全員をまとめて装備します。未装備品と編成中の装備を組み直し、待機中の仲間の装備は外しません。新しい装備を獲得したら見直しましょう。</p>
<h2>装備の集め方</h2><ul><li><b>通常ダンジョン：</b>装備ドロップが設定された依頼をクリア。依頼・ダンジョンのページで戦利品を確認してください。</li><li><b>季節イベント：</b>ボス撃破時に65%で専用3アイテムから1個を抽選。単独はドロップ時に獲得、アライアンスは参加パーティのダイスで獲得者を決定します。F〜Dは控えめな装備、C以上はレアな限定装備や装飾品を狙えます。</li><li><b>釣り桟橋：</b>装飾品を入手して有効化すると、アプリを閉じている間も1時間ごとに5%で通常装備1個。獲得時のレア度は★50%・★★35%・★★★15%です。</li></ul><p>ストーリーでは装備はドロップしません。装備集めは酒場の依頼やイベントを活用しましょう。</p><p><a href="#formation">パーティ編成のやり方 →</a> / <a href="#equipment">装備・アイテム一覧 →</a> / <a href="#contracts">酒場・依頼 →</a></p>
`],
 formation:['パーティ編成',`<p>仲間画面で最大6人を前衛・中衛・後衛に2人ずつ配置します。</p><h2>仲間から枠を選ぶ</h2><p>仲間をタップ →「編成する」または「配置を変更」→ 枠を選択。編成済みの枠なら入れ替えます。</p><h2>空き枠から仲間を選ぶ</h2><p>空き枠をタップして、待機中の仲間を選びます。編成中のキャラをタップ →「編成から外す」で空き枠を作れます。最後の1人は外せません。</p><h2>自動編成</h2><p>「自動編成」→「自動で編成する」で確定。現在のレベル・装備込みの能力値で選びます。</p><ul><li>前衛：主人公を必ず配置。残りはタンク・アタッカーのHPが高い順。</li><li>中衛：未配置のアタッカー・バッファー・デバッファーの攻撃力が高い順。</li><li>後衛：ヒーラーをHPが高い順に優先。</li></ul><p>役割に合う仲間を先に配置し、不足枠は他の未配置キャラから補います。前衛・後衛はHP、中衛は攻撃力を比較。同じキャラは重複配置しません。</p><h2>自動装備</h2><p>「自動装備」→「自動で装備する」で編成中の全員の装備を見直します。未装備の所持品と編成中の装備を対象に、パーティ順に戦闘力が高くなる装備を割り当てます。装備の重複使用はせず、待機中の仲間の装備は外しません。</p><h2>ソート設定</h2><p>LV・Rare（★の数）・入手順を選べます。前回の選択は端末に保存され、再起動後も引き継ぎます。</p><h2>回復役</h2><p>通常スキルの回復は単体で、攻撃力の0.5〜1.5倍（発動ごとにランダム）。必殺技の回復は★5が全体回復、★3・★4が単体回復。★4は★3より回復倍率が高くなります。自動回復は自パーティの誰かがHP80％未満でCT・SP条件を満たしたとき。単体回復はHP割合が最も低い仲間を対象にします。蘇生は戦闘不能の仲間が対象です。</p>
`],
 camp:['キャンプと装飾品',`<p>キャンプは次の冒険に備える拠点。キャラの行動・会話を眺めながら、仲間の編成や装備を整えます。</p><h2>放置中のチャージ</h2>${table(['資源','基本間隔','上限'],[['スタミナ','10分で1','10（装飾で増加）'],['星の石','30分で1','所持上限なし']])}<p>アプリ終了中も最終保存時刻と経過時間から再開時に精算します。チャージ途中の時間も持ち越します。</p><h2>放置経験値とは</h2><p>チュートリアル完了後、アプリが非表示の間は編成中の仲間に基本10分で1 EXPが入ります。放置経験値＋10％の装飾品を有効にすると、100分で10 EXPのところが11 EXPになります。端数は持ち越します。キャンプ画面を開いたままの時間は対象外です。</p><h2>キャンプバフ</h2><p>所持装飾品から最大2個を有効化。回復時間短縮・最大スタミナ増加・放置経験値など、目的に合わせて選びます。同一装飾品の重複所持はできません。</p>${table(['装飾品','効果'],D.decorations.map(i=>[itemLink(i.id),esc(i.description)]))}<h2>データ移行</h2><p>メニュー → その他からセーブをZIPでエクスポート。移行先のタイトル画面でZIPを選び、内容を確認してインポートします。</p>`],
 story:['ストーリー',`<h2>第11章：大型ボス出現</h2><p>第10章クリア後、酒場の店主から大型ボス出現の知らせが届きます。「仲間を募集して、大勢で倒しに行こう！」という呼びかけを受け、各ランクの第11章へ挑みます。</p><p>全10階層・スタミナ0。単独でも挑戦できますが、ボスHPは同ランク第10章の約3.6倍の長期戦仕様です。回復役・装備を整えて共闘で挑みましょう。</p><p>「仲間を募集して出発する」で最大30秒の募集を開始。NPCや登録済みフレンドのパーティがランダムで参加し、最大3パーティ・18人で攻略します。2パーティ参加または時間切れで出発。参加者や強いフレンドが必ず来るとは限りません。通信によるリアルタイムマルチではありません。</p><p>第11章の初回討伐で星の石30個。単独・共闘で共通の1回限りです。再クリアでは少量のEXP・Gを獲得します。</p>
<p>各ランク11章、全77章。スタミナ消費0で物語とダンジョンに挑みます。5章・10章は10階層で、最深部に巨大ボスが待ち受けます。</p><p>クリアごとに少量のEXP・G。第1〜10章は初回のみ星の石5個、第11章は初回のみ30個を獲得します。必要ランクに届かないときは酒場の依頼でRPを集めましょう。</p>${table(['ランク','通常章EXP / G','5・10章EXP / G'],D.ranks.map((r,i)=>[r.name,`${5+2*i} / ${10+5*i}`,`${(5+2*i)*2} / ${(10+5*i)*2}`]))}<p class="note">以下には章タイトル・ボス名を含みます。</p>${D.ranks.map(r=>`<details class="panel"><summary>${r.name}ランクの11章</summary>${table(['章','タイトル','階層','ボス'],D.campaign.filter(c=>c.rank===r.name).map(c=>[c.chapter,esc(c.title),c.floors,esc(c.bossName||'—')]))}</details>`).join('')}`],
 systems:['戦闘システム・データ',`<h2>属性相性</h2><p>火 → 風 → 水 → 火の順で有利。光と闇は互いに有利です。通常攻撃にもスキルにも属性が乗ります。</p>${table(['攻撃側＼防御側',...Object.values(E)],Object.keys(E).map(a=>[E[a],...Object.keys(E).map(b=>a===b?'1.00倍':beats[a]===b?'1.25倍':beats[b]===a?'0.75倍':'1.00倍')]))}<h2>ボスのスキルCT</h2>${table(['挑戦ランク','ボスのCT'],[...'FEDCBAS'].map((r,i)=>[r,`${16-i}〜${17.5-i}秒`]))}<p>初回とスキル使用ごとにランダムで決定。ゲーム内ではボスのCTは非表示です。前方範囲と全体攻撃はCTを共有します。</p><h2>雑魚敵の範囲スキルCT</h2>${table(['階層','クールタイム'],[5,6,7,8,9,10].map(f=>[f,`${25-f}秒`]))}<p>雑魚は前方範囲1.1倍。ボスは前方範囲1.4倍・全体1.2倍を共有CTで交互に使用します。前衛が倒れたパーティは次の生存列が前方範囲の対象になります。</p><h2>スキルとSP</h2><p>CTが0でも必要SPが足りなければ発動できません。消費SP、対象、倍率はキャラ個別ページで確認してください。</p><h2>ダメージの読み方</h2><p>攻撃力・スキル倍率・属性相性に加え、防御、タンク補正、バフ・デバフ、装備効果、回避などが反映されます。表の倍率は最終ダメージが常に同じ比率で増えることを保証する値ではありません。</p><h2>編成の出発点（攻略の提案）</h2><p>タンク1・火力2・魔法1・回復1・支援1を出発点に、敵の属性と範囲攻撃に合わせて変更します。低レアでも回復・防御・有利属性の役割を優先する価値があります。</p>`],
 faq:['よくある質問',`<h2>星の石は課金しないと増えない？</h2><p>30分で1個自動チャージされます。ログインボーナスやストーリー初回クリアでも入手できます。</p><h2>ログインスタンプは？</h2><p>連続ログインで星の石20・25・30・35・40個。5日目を受け取ると1日目に戻ります。日付の切替は日本時間0:00です。</p><h2>イベントは低ランクでも参加できる？</h2><p>F〜Dは5階層、C以上は10階層です。全ランクでアライアンスを募集できます。</p><h2>フレンドはリアルタイムで操作している？</h2><p>いいえ。QRで共有された情報を使った擬似マルチです。</p><h2>ストーリーで育成できる？</h2><p>少量のEXP・Gが入ります。本格的な育成とランク上げは酒場の依頼が中心です。</p><h2>Wikiとゲームで数値が違うときは？</h2><p>上部のデータ更新日を確認してください。本Wikiはゲームのマスターを同期して作る静的サイトです。公開後の変更は同期作業が必要です。</p><h2>用語集</h2>${table(['用語','意味'],[['RP','依頼達成で増えるパーティランク用ポイント'],['CT','次のスキル発動までの待ち時間'],['SP','スキル発動に関わるポイント。キャラごとに必要量が異なる'],['EXP','レベルアップに必要な経験値'],['アライアンス','最大3パーティ・18人の共闘編成']])}`]
};const c=content[page];return c?`<div class="prose"><span class="eyebrow">FIELD GUIDE</span><h1>${c[0]}</h1>${c[1]}</div>`:missing();}
function searchPage(query){const q=query.trim().toLowerCase(),items=[...D.characters.map(c=>({type:'character',id:c.id,title:c.name,kind:'キャラ',text:c.skill+' '+c.skillDescription})),...D.events.map(e=>({type:'event',id:e.id,title:e.boss,kind:'イベント',text:e.theme})),...D.equipment.map(i=>({type:'equipment',id:i.id,title:i.name,kind:'装備',text:i.description})),...D.decorations.map(i=>({type:'equipment',id:i.id,title:i.name,kind:'装飾品',text:i.description})),...D.contracts.map(c=>({type:'contract',id:c.id,title:c.name,kind:'依頼',text:c.description})),...D.dungeons.map(d=>({type:'dungeon',id:d.id,title:d.name,kind:'ダンジョン',text:d.subtitle})),...D.npcs.map(n=>({type:'npc',id:n.id,title:n.name,kind:'NPC',text:n.personality}))];const found=q?items.filter(i=>(i.title+' '+i.text).toLowerCase().includes(q)):[];return `<h1>「${esc(query)}」の検索結果</h1><p class="count">${found.length}件</p><div class="linklist">${found.map(i=>`<a href="#${i.type}/${encodeURIComponent(i.id)}">${tag(i.kind)} <b>${esc(i.title)}</b><p class="note">${esc(i.text||'').slice(0,130)}</p></a>`).join('')||'<p class="empty">キーワードを変えて検索してください。</p>'}</div>`;}
function missing(){return '<h1>ページが見つかりません</h1><p><a href="#home">トップへ戻る →</a></p>';}

// Editorial comparison model, not simulated combat DPS. Assumptions: three enemies,
// six allies, average ally HP 240 / ATK 35. CT availability includes SP cost.
function rankingFeatures(c){
 const f={attack:c.atk,durability:c.hp*(1+c.def/30),damage:0,healing:0,guard:0,buff:0,debuff:0};
 const seasonal=!!c.seasonalUltimate;
 const skills=seasonal?[c.normalSkill,{...c.seasonalUltimate,cost:c.ability?.cost}]:[c.ability||{}];
 for(const a of skills){
  const ct=Math.max(1,a.cooldown||12)*(1+(a.cost||0)/20),uptime=Math.min(1,(a.duration||0)/ct);
  const enemies=a.target==='enemies'||a.scope==='敵全体'?3:1, allies=a.target==='allies'||a.scope==='味方全体'?6:1;
  const heal=a.heal||(!seasonal&&c.role==='Healer'?a.power:0)||0;
  const power=!seasonal&&['Healer','Buffer'].includes(c.role)?0:(a.power||0);
  const damage=c.atk*power*(a.hits||1)*enemies/ct*(1+(a.bossBonus||0)/2+(a.ignoreDefense||0)*.2+(a.sureHit?.05:0));
  f.damage+=damage+(a.dot?c.atk*.15*(a.dotDuration||0)/ct:0);
  f.healing+=(c.atk*heal+240*(a.regen||0)*(a.duration||0)/2)*allies/ct+240*(a.revive||0)/ct+damage*(a.lifesteal||0);
  f.guard+=(a.shield||0)*240*allies/ct+(a.evade||0)*20/ct+(a.taunt?10*uptime:0);
  for(const [b,n] of [[a.buff,allies],[a.selfBuff,1],[a.partyBuff,6]])if(b){
   f.buff+=35*n*uptime*((b.attack||0)+(b.speed||0)+(b.critical||0)*.5);
   f.guard+=20*n*uptime*((b.defense||0)*.5+(b.reduction||0));
  }
  if(!seasonal&&c.role==='Buffer')f.buff+=35*6*Math.max(0,(a.power||1)-1)*uptime;
  if(a.selfRegen)f.healing+=c.hp*a.selfRegen*(a.selfRegenDuration/2)/ct;
  if(a.effect==='selfDefense')f.guard+=20*Math.max(0,(a.defenseMultiplier||1)-1)*uptime;
  const d=a.debuff||{};
  f.debuff+=35*enemies*uptime*((d.vulnerable||0)+(d.defenseDown||0)*.5+(d.slow||0)+(d.blind||0));
  f.debuff+=20*enemies*((a.stun||0)*(a.freezeChance??1)+(a.ctDelay||0))/ct;
  if(!seasonal&&c.role==='Debuffer')f.debuff+=35*enemies*6/ct*.2;
  if(a.randomDebuff)f.debuff+=35*.2*uptime;
  if(a.randomBuff)f.buff+=35*allies*.2*uptime;
  f.buff+=35*allies*(a.ctReduce||0)/ct;
  if(a.cleanse)f.healing+=10*allies/ct;
  if(a.resetNormal)f.damage+=c.atk*(c.normalSkill?.power||0)*(c.normalSkill?.hits||1)/ct;
  if(a.killRefund)f.damage+=damage*a.killRefund*.25;
 }
 return f;
}
function rankCharacters(characters,role){
 const weights={Attacker:{attack:.25,damage:.55,durability:.1,guard:.05,debuff:.05},Sorcerer:{attack:.2,damage:.55,debuff:.15,durability:.1},Tank:{durability:.35,guard:.4,debuff:.1,damage:.1,healing:.05},Healer:{healing:.6,durability:.15,buff:.15,guard:.1},Buffer:{buff:.55,healing:.15,guard:.15,durability:.15},Debuffer:{debuff:.55,damage:.25,durability:.1,attack:.1}}[role];
 const entries=characters.filter(c=>c.role===role).map(c=>({c,f:rankingFeatures(c)}));
 const maxima=Object.fromEntries(Object.keys(weights).map(k=>[k,Math.max(1,...entries.map(e=>e.f[k]))]));
 return entries.map(({c,f})=>({...c,rankingScore:Math.round(10000*Object.entries(weights).reduce((sum,[k,w])=>sum+w*f[k]/maxima[k],0))/100})).sort((a,b)=>b.rankingScore-a.rankingScore||a.id.localeCompare(b.id));
}

function rankingPage(selected='Attacker'){
 const role=roles[selected]?selected:'Attacker';
 const list=rankCharacters(D.characters,role);
 return `<span class="eyebrow">ROLE RANKINGS</span><h1>${roles[role]}ランキング</h1><p>同じ役割の仲間を、スキル構成や育成前の基礎能力で比較できます。キャラを選ぶとスキルや入手方法を確認できます。</p><div class="filterbar">${Object.entries(roles).map(([id,name])=>`<a class="button" href="#rankings/${id}" ${id===role?'aria-current="page"':''}>${name}</a>`).join('')}</div><section class="panel"><h2>評価基準：</h2><p>スキル構成やLv1・装備なしの初期攻撃力の高さなどの総合値で判断しています。</p><p class="note">役割別の重み付けによるWiki独自の参考評価です。実戦の勝率を測定したものではありません。属性相性・スキルの対象やCT・装備・編成によって実戦での有用性は変わります。限定キャラと常設キャラを含みます。</p></section><div class="grid">${list.map((c,i)=>{const rank=list.findIndex(x=>x.rankingScore===c.rankingScore)+1;return `<article class="card"><div class="card-body"><span class="badge">${rank}位</span></div><a href="#character/${c.id}"><div class="portrait-wrap">${portrait(c)}</div><div class="card-body"><h2>${esc(c.name)}</h2><p>${el(c.el)} · ${'★'.repeat(c.rarity)} · ${c.eventOnly?'限定':'常設'}</p><p>HP ${c.hp} / 攻撃 ${c.atk} / 防御 ${c.def}</p><h3>${esc(c.normalSkill?.name||c.skill)}</h3><p>${esc(c.normalSkill?.description||c.skillDescription||c.ability?.scope||'詳しいスキルはキャラページへ')}</p><p class="note">${esc(skillPower(c,c.normalSkill||c.ability||{},!!c.normalSkill))}</p></div></a></article>`}).join('')}</div>`;
}

function render(){let [page='home',...parts]=location.hash.slice(1).split('/');page||='home';let id;try{id=decodeURIComponent(parts.join('/'));}catch{id='';}const parent={character:'characters',event:'events',dungeon:'dungeons',contract:'contracts',npc:'npcs'}[page]||page;$('#navigation').innerHTML=navigation.map(([p,i,n])=>`<a href="#${p}" ${p===parent?'aria-current="page"':''}>${i}　${n}</a>`).join('');const views={home,rankings:()=>rankingPage(id),characters,character:()=>characterPage(id),events,event:()=>eventPage(id),dungeons,dungeon:()=>dungeonPage(id),contracts:contractsPage,contract:()=>contractPage(id),equipment:()=>equipmentPage(id),gacha:gachaPage,npcs:()=>npcPage(),npc:()=>npcPage(id),search:()=>searchPage(id)};try{$('#main').innerHTML=views[page]?views[page]():guides(page);}catch(error){console.error(error);$('#main').innerHTML='<h1>ページの読み込みに失敗しました</h1><a href="#home">トップへ戻る</a>';}document.title=($('#main h1')?.textContent||'トップ')+' | ダンジョンの入口でキャンプでもしようよ。攻略Wiki';if(page==='characters'){document.querySelectorAll('.filterbar input,.filterbar select').forEach(e=>e.addEventListener('input',filterCharacters));filterCharacters();}if(page==='contracts'){document.querySelectorAll('.filterbar input,.filterbar select').forEach(e=>e.addEventListener('input',filterJobs));filterJobs();}if(page==='equipment'&&!id){document.querySelectorAll('.filterbar input,.filterbar select').forEach(e=>e.addEventListener('input',filterItems));filterItems();}updateClocks();window.scrollTo(0,0);}
function updateClocks(){document.querySelectorAll('[data-countdown]').forEach(e=>{const seconds=Math.max(0,Math.floor((Number(e.dataset.countdown)-Date.now())/1000));e.textContent=`終了まで ${Math.floor(seconds/86400)}日 ${Math.floor(seconds%86400/3600)}時間 ${Math.floor(seconds%3600/60)}分`;});}
$('.skip').addEventListener('click',e=>{e.preventDefault();$('#main').focus();});
$('#searchform').addEventListener('submit',e=>{e.preventDefault();location.hash='search/'+encodeURIComponent($('#global-search').value);});window.addEventListener('hashchange',render);let calendarKey='';setInterval(()=>{const n=nowJST(),key=`${n.getUTCFullYear()}-${n.getUTCMonth()}-${n.getUTCDate()}`;if(calendarKey&&key!==calendarKey)render();calendarKey=key;updateClocks();},1000);render();
